import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { routes } from "../src/server/api/index.js";

/**
 * Writes src/client/routes.ts: every route's method and path by name, the
 * one runtime table the client needs (types come from the server). Run
 * after adding or changing a route: `npm run gen:client`. The protocol
 * test fails while the file is stale.
 */
export function clientRoutesSource(): string {
  const lines = [...routes]
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((r) => `  ${JSON.stringify(r.name)}: [${JSON.stringify(r.method)}, ${JSON.stringify(r.path)}${r.raw ? ', "raw"' : r.upload ? ', "upload"' : ""}],`);
  return `// Generated by scripts/gen-client-routes.ts from src/server/api — do not edit; run \`npm run gen:client\`.
/** Route name → [method, path pattern, and "raw" (answers a stream or a file) or "upload" (sends file bytes): both HTTP only]. */
export const ROUTES = {
${lines.join("\n")}
} as const;
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  writeFileSync(new URL("../src/client/routes.ts", import.meta.url), clientRoutesSource());
  console.log(`src/client/routes.ts: ${routes.length} routes`);
}
